name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List contents of root
      run: |-
          ls -la
          cd client
          ls -la

    - name: List contents
      run: |-
          ls -la

    # - uses: pnpm/action-setup@v4
    #   name: Install pnpm
    #   with:
    #     version: 8
    #     run_install: |
    #       - recursive: true
    #         args: [--frozen-lockfile, --strict-peer-dependencies]

    # - name: Install dependencies
    #   run: pnpm install --frozen-lockfile

    # - name: Create .env.local
    #   run: |
    #     touch .env.local
    #     echo VITE_BE_URL=$VITE_BE_URL >> .env.local
    #   env:
    #     VITE_BE_URL: ${{ secrets.VITE_BE_URL }}

    # - name: Build website
    #   run: |-
    #       pnpm build
    #       > dist/.nojekyll

    # - name: Deploy website
    #   uses: JamesIves/github-pages-deploy-action@v4
    #   with:
    #     branch: gh-pages
    #     folder: dist
