name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Create .env.local
      run: |
        touch .env.local
        echo VITE_BE_URL=$VITE_BE_URL >> .env.local
      env:
        VITE_BE_URL: ${{ secrets.VITE_BE_URL }}

    - name: Build website
      run: |-
          pnpm build
          > dist/.nojekyll

    - name: Deploy website
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./client/dist
